# Generated by Django 5.1.5 on 2025-04-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceregistry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deviceregistry',
            name='updated_at',
        ),
    ]
