# Generated by Django 5.1.5 on 2025-04-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0002_remove_deviceregistry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviceregistry',
            table='registered_devices',
        ),
    ]
