# Generated by Django 5.1.5 on 2025-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0003_alter_deviceregistry_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
    ]
