# Generated by Django 5.1.5 on 2025-04-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0004_instancecredentials'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviceregistry',
            table='devices',
        ),
    ]
