# Generated by Django 5.1.5 on 2025-04-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0005_alter_deviceregistry_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deviceregistry',
            constraint=models.UniqueConstraint(fields=('ip', 'port'), name='unique_ip_port_pair'),
        ),
    ]
