# Generated by Django 5.1.5 on 2025-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0006_deviceregistry_unique_ip_port_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
    ]
