# Generated by Django 5.1.5 on 2025-05-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0007_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregistry',
            name='configuracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='device_registry.configuracion'),
        ),
    ]
