# Generated by Django 5.1.5 on 2025-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0008_deviceregistry_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancecredentials',
            name='instance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='instancecredentials',
            unique_together={('instance', 'username')},
        ),
    ]
